#!/bin/bash

./Allclean

blockMesh

buoyantSimpleFoam > log #&

# sleep 3
# echo "CTRL+C to abort the Residual-Task"
# foamMonitor -l postProcessing/residuals/0/residuals.dat
# sleep 1

buoyantSimpleFoam -postProcess -func sample -latestTime
buoyantSimpleFoam -postProcess -latestTime -func wallShearStress
buoyantSimpleFoam -postProcess -latestTime -func wallHeatFlux
buoyantSimpleFoam -postProcess -latestTime -func yPlus

./createProfiles.py
./skin_friction.py
./nusselt_number.py

