#!/bin/sh
#SBATCH --partition=multiple
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=32
#SBATCH --time=12:00:00
#SBATCH --mail-type=ALL
module load compiler/intel/19.1
module load mpi/openmpi/4.0 
echo "Runnning in "$SLURM_SUBMIT_DIR
cd $SLURM_SUBMIT_DIR
mpirun --bind-to core --map-by core -report-bindings xcompact3d
echo "Finished."
