#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

foamCleanTutorials
touch foam.foam
runApplication blockMesh

runApplication $(getApplication)

simpleFoam -postProcess -func R -latestTime
postProcess -func sample -latestTime
