#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Clean time directories
rm -rf *[1-9]*
rm -f log.* 2>/dev/null

# Clean dynamicCode
rm -r dynamicCode

# Clean PostProcessing
rm -r postProcessing

# Clean Log files
rm log*


#------------------------------------------------------------------------------
