#!/bin/bash
# remove the inital directory and copy from 0.orig
./Allclean
rm -rf 0
cp -r 0.org 0

# createMesh
./makeMesh

# operate setFields routine on 0-directory
# setFields | tee log.setFields

# run pisoFoam in non-parallel mode
pisoFoam | tee log.pisoFoam

# run pisoFoam in parallel mode
# decomposePar
# mpirun.openmpi -np 2 pisoFoam -parallel > log.pisoFoam 
# reconstructPar

./createGraph.py

